/*
 *
 */
package com.stayprime.basestation2.tournament.ui;

import ca.odell.glazedlists.gui.TableFormat;
import com.stayprime.tournament.model.Player;
import com.stayprime.ui.editor.ListEditor;
import javax.swing.ListSelectionModel;

/**
 *
 * @author benjamin
 */
public class PlayerListEditor extends ListEditor<Player> {

    public PlayerListEditor() {
        initComponents();
        setTableFormat(new PlayerListTableFormat());
        setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    protected void setupTableColumns() {
        getTable().getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private static class PlayerListTableFormat implements TableFormat<Player> {
        @Override
        public int getColumnCount() {
            return 1;
        }

        @Override
        public String getColumnName(int column) {
            int i = 0;
            if (column == i++) return "Name";
            if (column == i++) return "Cart";
            throw new IllegalArgumentException();
        }

        @Override
        public Object getColumnValue(Player p, int column) {
            int i = 0;
            if (column == i++) return p.getName();
            if (column == i++) return p.getCart();
            throw new IllegalArgumentException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 32), new java.awt.Dimension(1, 32), new java.awt.Dimension(1, 32));

        setButtonsPanelVisible(false);
        setName("Form"); // NOI18N
        getContainerDelegate().setLayout(new javax.swing.BoxLayout(getContainerDelegate(), javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(PlayerListEditor.class);
        titleLabel.setFont(titleLabel.getFont().deriveFont(titleLabel.getFont().getStyle() | java.awt.Font.BOLD, titleLabel.getFont().getSize()+2));
        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N
        getContainerDelegate().add(titleLabel);

        filler1.setName("filler1"); // NOI18N
        getContainerDelegate().add(filler1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
