/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateUserDialog.java
 *
 * Created on 25/05/2011, 10:44:33 AM
 */

package com.stayprime.basestation2.ui.dialog;

import java.awt.Window;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.application.Action;

/**
 *
 * @author benjamin
 */
public class CreateUserDialog extends javax.swing.JDialog {
    protected boolean confirmed = false;

    protected boolean validData = false;
    public static final String PROP_VALIDDATA = "validData";

    /** Creates new form CreateUserDialog */
    public CreateUserDialog(java.awt.Window parent, boolean modal) {
        super(parent);
        initComponents();
	setModal(modal);

	DocumentListener dl = new DocumentListener() {

	    public void insertUpdate(DocumentEvent e) {
		changedUpdate(e);
	    }

	    public void removeUpdate(DocumentEvent e) {
		changedUpdate(e);
	    }

	    public void changedUpdate(DocumentEvent e) {
		setValidData(
			nameField.getText().isEmpty() == false 
                        && userTextField.getText().isEmpty() == false
			&& passwordField.getPassword().length > 0
			&& new String(passwordField.getPassword())
			.equals(new String(confirmPasswordField.getPassword())));
	    }
	};
        
        nameField.getDocument().addDocumentListener(dl);
	userTextField.getDocument().addDocumentListener(dl);
	passwordField.getDocument().addDocumentListener(dl);
	confirmPasswordField.getDocument().addDocumentListener(dl);
    }

    public static CreateUserDialog showCreateUserDialog(Window parent, String title, String user, boolean disableUserEditing, boolean createUsersOption) {
	CreateUserDialog dialog = new CreateUserDialog(parent, true);
	dialog.pack();
	dialog.setLocationRelativeTo(parent);

	if(title != null)
	    dialog.setTitle(title);

	if(user != null)
	    dialog.userTextField.setText(user);

	if(disableUserEditing)
	    dialog.userTextField.setEditable(!disableUserEditing);
	
	dialog.allowCreateUsersCheckBox.setVisible(createUsersOption);

	dialog.setVisible(true);
	dialog.dispose();

	return dialog;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passLabel = new javax.swing.JLabel();
        confirmPassLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        userTextField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        allowCreateUsersCheckBox = new javax.swing.JCheckBox();
        createAdminUserButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(CreateUserDialog.class);
        setTitle(resourceMap.getString("CreateUserDialog.title")); // NOI18N
        setModal(true);
        setName("CreateUserDialog"); // NOI18N

        passLabel.setText(resourceMap.getString("passLabel.text")); // NOI18N
        passLabel.setName("passLabel"); // NOI18N

        confirmPassLabel.setText(resourceMap.getString("confirmPassLabel.text")); // NOI18N
        confirmPassLabel.setName("confirmPassLabel"); // NOI18N

        passwordField.setColumns(16);
        passwordField.setName("passwordField"); // NOI18N

        confirmPasswordField.setColumns(16);
        confirmPasswordField.setName("confirmPasswordField"); // NOI18N

        userTextField.setColumns(16);
        userTextField.setName("userTextField"); // NOI18N

        userLabel.setText(resourceMap.getString("userLabel.text")); // NOI18N
        userLabel.setName("userLabel"); // NOI18N

        allowCreateUsersCheckBox.setText(resourceMap.getString("allowCreateUsersCheckBox.text")); // NOI18N
        allowCreateUsersCheckBox.setName("allowCreateUsersCheckBox"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(CreateUserDialog.class, this);
        createAdminUserButton.setAction(actionMap.get("createUser")); // NOI18N
        createAdminUserButton.setText(resourceMap.getString("createAdminUserButton.text")); // NOI18N
        createAdminUserButton.setName("createAdminUserButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancel")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        nameField.setColumns(16);
        nameField.setName("nameField"); // NOI18N

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cancelButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createAdminUserButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userLabel)
                                        .addComponent(passLabel)
                                        .addComponent(confirmPassLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(allowCreateUsersCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassLabel)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allowCreateUsersCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAdminUserButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action(enabledProperty=PROP_VALIDDATA)
    public void createUser() {
	confirmed = true;
	setVisible(false);
    }

    @Action
    public void cancel() {
	confirmed = false;
	setVisible(false);
    }

    public boolean isValidData() {
	return validData;
    }

    protected void setValidData(boolean validData) {
	boolean oldValidData = this.validData;
	this.validData = validData;
	firePropertyChange(PROP_VALIDDATA, oldValidData, validData);
    }

    public boolean isConfirmed() {
	return confirmed;
    }

    public boolean isCreateUsersAllowed() {
	return allowCreateUsersCheckBox.isSelected();
    }

    public String getName() {
	return nameField.getText();
    }
    
    public String getUserName() {
	return userTextField.getText();
    }

    public char[] getPassword() {
	return passwordField.getPassword();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowCreateUsersCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JButton createAdminUserButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables

}
