/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stayprime.basestation2.ui.cartassignment;

import com.ezware.dialog.task.TaskDialogs;
import com.stayprime.basestation2.BaseStation2App;
import com.stayprime.basestation2.services.CartService;
import com.stayprime.hibernate.entities.CartAssignment;
import com.stayprime.hibernate.entities.CartInfo;
import com.stayprime.ui.editor.EditorPanel;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author benjamin
 */
public class CartAssignmentEditor extends EditorPanel<Object> {

    private JDialog dialog;

    CartService cartService;

    /**
     * Creates new form CartAssignmentEditor
     */
    public CartAssignmentEditor() {
        initComponents();
    }

    public void setCartService(CartService cartService) {
        this.cartService = cartService;
    }

    private void showDialog() {
        BaseStation2App app = BaseStation2App.getApplication();
        if (dialog == null) {
            JFrame mainFrame = app.getMainFrame();
            dialog = new JDialog(mainFrame, "Cart Assignments", true);
            dialog.setContentPane(this);
            dialog.pack();
        }
        app.show(dialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartListEditor = new com.stayprime.basestation2.ui.cartassignment.CartListEditor();
        bottomRow = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        saveButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        cartListEditor.setName("cartListEditor"); // NOI18N
        add(cartListEditor, java.awt.BorderLayout.CENTER);

        bottomRow.setName("bottomRow"); // NOI18N
        bottomRow.setLayout(new javax.swing.BoxLayout(bottomRow, javax.swing.BoxLayout.LINE_AXIS));

        filler1.setName("filler1"); // NOI18N
        bottomRow.add(filler1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(CartAssignmentEditor.class, this);
        saveButton.setAction(actionMap.get("save")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N
        bottomRow.add(saveButton);

        add(bottomRow, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    @Action(block = Task.BlockingScope.APPLICATION)
    public Task load() {
        return new LoadTask(org.jdesktop.application.Application.getInstance());
    }

    private class LoadTask extends Task<List<CartAssignment>, Void> {
        private List<CartInfo> carts;
        LoadTask(org.jdesktop.application.Application app) {
            super(app);
        }
        @Override protected List<CartAssignment> doInBackground() {
            this.carts = cartService.listCartsAndUnits();
            return cartService.listCartAssignments();
        }
        @Override protected void succeeded(List<CartAssignment> result) {
            cartListEditor.setCarts(carts);
            cartListEditor.setCartAssignments(result);
            showDialog();
        }
        @Override
        protected void failed(Throwable t) {
            TaskDialogs.showException(t);
        }
    }

    @Action(block = Task.BlockingScope.APPLICATION)
    public Task save() {
        return new SaveTask(org.jdesktop.application.Application.getInstance());
    }

    private class SaveTask extends Task<Object, Void> {
        private final List<CartAssignment> list;
        SaveTask(org.jdesktop.application.Application app) {
            super(app);
            this.list = cartListEditor.getCartAssignments();
        }
        @Override protected Object doInBackground() {
            cartService.saveCartAssignments(list);
            return null;
        }
        @Override protected void succeeded(Object result) {
            if (dialog != null) {
                dialog.setVisible(false);
            }
        }
        @Override
        protected void failed(Throwable t) {
            TaskDialogs.showException(t);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomRow;
    private com.stayprime.basestation2.ui.cartassignment.CartListEditor cartListEditor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
