package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.stayprime.util.gson.Exclude;

/**
 * Ads generated by hbm2java
 */
@Entity
@Table(name = "ads")
public class Ads implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ad_id", unique = true, nullable = false)
    private Integer adId;

    private int category;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id", nullable = false)
    @Exclude
    private Clients clients;

    private String name;

    private String description;

    @Column(nullable = false)
    private int type;

    private String source;

    @Temporal(TemporalType.DATE)
    private Date startDate;

    @Temporal(TemporalType.DATE)
    private Date endDate;

    private String holeAd;

    private String adZone;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false)
    private Date updated;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "ads", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Contracts> contractses = new HashSet(0);

    public Ads() {
    }

    public Ads(int categories, Clients clients, String name, int type, Date updated) {
        this.category = categories;
        this.clients = clients;
        this.name = name;
        this.type = type;
        this.updated = updated;
    }

    public Ads(int categories, Clients clients, String name, String description, int type, String source, Date updated, Set contractses) {
        this.category = categories;
        this.clients = clients;
        this.name = name;
        this.description = description;
        this.type = type;
        this.source = source;
        this.updated = updated;
        this.contractses = contractses;
    }

    public Integer getAdId() {
        return this.adId;
    }

    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    public int getCategory() {
        return this.category;
    }

    public void setCategory(int categories) {
        this.category = categories;
    }

    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getHoleAd() {
        return holeAd;
    }

    public void setHoleAd(String holeAd) {
        this.holeAd = holeAd;
    }

    public String getAdZone() {
        return adZone;
    }

    public void setAdZone(String adZone) {
        this.adZone = adZone;
    }

    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public Set<Contracts> getContractses() {
        return this.contractses;
    }

    public void setContractses(Set contractses) {
        this.contractses = contractses;
    }

    public boolean isActive() {
        return isActive(new Date());
    }

    public boolean isActive(Date when) {
        for (Contracts contract : getContractses()) {
            if (contract.isActive(when.getTime())) {
                return true;
            }
        }

        return false;
    }

    public static List<Ads> findActive(Collection<Ads> list, Date date) {
        ArrayList<Ads> active = new ArrayList<Ads>();
        if (list != null) {
            for (Ads ad : list) {
                if (ad.isActive()) {
                    active.add(ad);
                }
            }
        }
        return active;
    }

    public void setParents() {
        for (Contracts cs : contractses) {
            cs.setAds(this);
        }
    }
}
