package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adzones generated by hbm2java
 */
@Entity
@Table(name = "adzones")
public class Adzones implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(unique = true, nullable = false)
    private Integer adzoneId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "contract_id", nullable = false)
    private Contracts contracts;

    private Integer course;

    private Integer hole;

    private String name;

    @Column(columnDefinition = "LONGTEXT")
    private String shape;

    private Double shapeAlpha;

    private Integer color;

    private String extraInfo;

    public Adzones() {
    }

    public Adzones(Contracts contracts, String name) {
        this.contracts = contracts;
        this.name = name;
    }

    public Adzones(Contracts contracts, Integer course, Integer hole, String name, String shape, Double shapeAlpha, Integer color, String extraInfo) {
        this.contracts = contracts;
        this.course = course;
        this.hole = hole;
        this.name = name;
        this.shape = shape;
        this.shapeAlpha = shapeAlpha;
        this.color = color;
        this.extraInfo = extraInfo;
    }

    public Integer getAdzoneId() {
        return this.adzoneId;
    }

    public void setAdzoneId(Integer adzoneId) {
        this.adzoneId = adzoneId;
    }

    public Contracts getContracts() {
        return this.contracts;
    }

    public void setContracts(Contracts contracts) {
        this.contracts = contracts;
    }

    public Integer getCourse() {
        return this.course;
    }

    public void setCourse(Integer course) {
        this.course = course;
    }

    public Integer getHole() {
        return this.hole;
    }

    public void setHole(Integer hole) {
        this.hole = hole;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShape() {
        return this.shape;
    }

    public void setShape(String shape) {
        this.shape = shape;
    }

    public Double getShapeAlpha() {
        return this.shapeAlpha;
    }

    public void setShapeAlpha(Double shapeAlpha) {
        this.shapeAlpha = shapeAlpha;
    }

    public Integer getColor() {
        return this.color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public String getExtraInfo() {
        return this.extraInfo;
    }

    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }

}
