package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CartTrackingId generated by hbm2java
 */
@Embeddable
public class CartTrackingId implements java.io.Serializable {

    @Column(nullable = false)
    private int cartNumber;

    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date timestamp;

    public CartTrackingId() {
    }

    public CartTrackingId(int cartNumber, Date timestamp) {
        this.cartNumber = cartNumber;
        this.timestamp = timestamp;
    }

    public int getCartNumber() {
        return this.cartNumber;
    }

    public void setCartNumber(int cartNumber) {
        this.cartNumber = cartNumber;
    }

    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CartTrackingId))
            return false;
        CartTrackingId castOther = (CartTrackingId) other;

        return (this.getCartNumber() == castOther.getCartNumber())
                && ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null && castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCartNumber();
        result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
        return result;
    }

}
