package com.stayprime.hibernate.entities;
// Generated Nov 27, 2014 1:54:45 PM by Hibernate Tools 4.3.1

import com.stayprime.localservice.Constants;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.apache.commons.lang.ObjectUtils;

/**
 * CartUnit generated by hbm2java
 */
@Entity
public class CartUnit implements java.io.Serializable {

    @Id @Column(unique = true, nullable = false)
    private String macAddress;

    private Integer cartNumber;

    private int status;

    private String ipAddress;

    private String simIp;

    private String simIccid;

    private String netAddress;

    @Temporal(TemporalType.TIMESTAMP)
    private Date simConnected;

    private String firmwareVersion;

    private String softwareVersion;

    @Temporal(TemporalType.TIMESTAMP)
    private Date ipUpdated;

    @Temporal(TemporalType.TIMESTAMP)
    private Date courseUpdated;

    @Temporal(TemporalType.TIMESTAMP)
    private Date pinlocationUpdated;

    @Temporal(TemporalType.TIMESTAMP)
    private Date adsUpdated;

    @Temporal(TemporalType.TIMESTAMP)
    private Date settingsUpdated;

    @Temporal(TemporalType.TIMESTAMP)
    private Date menuUpdated;

    @Transient //@Embedded
    private PropertiesColumn properties;

    public CartUnit() {
    }

    public String getMacAddress() {
        return this.macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    public Integer getCartNumber() {
        return cartNumber;
    }

    public void setCartNumber(Integer cartNumber) {
        this.cartNumber = cartNumber;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public boolean getStatusFlag(int flag) {
        return (status & flag) != 0;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getSimIp() {
        return this.simIp;
    }

    public void setSimIp(String simIp) {
        this.simIp = simIp;
    }

    public String getSimIccid() {
        return this.simIccid;
    }

    public void setSimIccid(String simIccid) {
        this.simIccid = simIccid;
    }

    public String getNetAddress() {
        return netAddress;
    }

    public void setNetAddress(String netIp) {
        this.netAddress = netIp;
    }

    public Date getSimConnected() {
        return simConnected;
    }

    public void setSimConnected(Date simConnected) {
        this.simConnected = simConnected;
    }

    public String getFirmwareVersion() {
        return this.firmwareVersion;
    }

    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion;
    }

    public String getSoftwareVersion() {
        return this.softwareVersion;
    }

    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion;
    }

    public Date getIpUpdated() {
        return this.ipUpdated;
    }

    public void setIpUpdated(Date ipUpdated) {
        this.ipUpdated = ipUpdated;
    }

    public Date getCourseUpdated() {
        return this.courseUpdated;
    }

    public void setCourseUpdated(Date courseUpdated) {
        this.courseUpdated = courseUpdated;
    }

    public Date getPinlocationUpdated() {
        return this.pinlocationUpdated;
    }

    public void setPinlocationUpdated(Date pinlocationUpdated) {
        this.pinlocationUpdated = pinlocationUpdated;
    }

    public Date getAdsUpdated() {
        return this.adsUpdated;
    }

    public void setAdsUpdated(Date adsUpdated) {
        this.adsUpdated = adsUpdated;
    }

    public Date getSettingsUpdated() {
        return this.settingsUpdated;
    }

    public void setSettingsUpdated(Date settingsUpdated) {
        this.settingsUpdated = settingsUpdated;
    }

    public Date getMenuUpdated() {
        return this.menuUpdated;
    }

    public void setMenuUpdated(Date menuUpdated) {
        this.menuUpdated = menuUpdated;
    }

    public PropertiesColumn getProperties() {
        return properties;
    }

    public static CartUnit find(List<CartUnit> list, String mac) {
        if (list == null) return null;
        for (CartUnit cu : list) {
            if (ObjectUtils.equals(cu.getMacAddress(), mac)) {
                return cu;
            }
        }
        return null;
    }

    public static CartUnit findByIpAddress(List<CartUnit> list, String ipAddress) {
        if (list == null) return null;
        for (CartUnit cu : list) {
            if (ObjectUtils.equals(cu.getIpAddress(), ipAddress)) {
                return cu;
            }
        }
        return null;
    }

    public static List<CartUnit> findBySimIccid(List<CartUnit> list, String simIccid) {
        if (list == null) return null;
        List<CartUnit> found = new ArrayList<CartUnit>();
        for (CartUnit cu : list) {
            if (ObjectUtils.equals(cu.getSimIccid(), simIccid)) {
                found.add(cu);
            }
        }
        return found;
    }

    public void setAssetUpdated(String key, Date assetUpdated) {
        switch (key) {
            case Constants.courseUpdated: setCourseUpdated(assetUpdated);
            break;
            case Constants.pinsUpdated: setPinlocationUpdated(assetUpdated);
            break;
            case Constants.adsUpdated: setAdsUpdated(assetUpdated);
            break;
            case Constants.menuUpdated: setMenuUpdated(assetUpdated);
            break;
        }
    }

}
