package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import java.util.Collections;
import java.util.Date;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.stayprime.util.gson.Exclude;

/**
 * Contracts generated by hbm2java
 */
@Entity
@Table(name = "contracts")
public class Contracts implements java.io.Serializable {

    @Id @GeneratedValue(strategy = IDENTITY)
    private Integer contractId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ad_id", nullable = false)
    @Exclude
    private Ads ads;

    @Temporal(TemporalType.DATE)
    private Date startDate;

    @Temporal(TemporalType.DATE)
    private Date endDate;

    private byte plan;

    private String holeAd;

    private String adZone;

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "contracts")
//    @Exclude
//    private Set<Adzones> adzoneses = new HashSet(0);

    public Contracts() {
    }

    public Contracts(Ads ads, Date startDate, Date endDate, byte plan) {
        this.ads = ads;
        this.startDate = startDate;
        this.endDate = endDate;
        this.plan = plan;
    }

    public Contracts(Ads ads, Date startDate, Date endDate, byte plan, String holeAd, String adZone, Set adzoneses) {
        this.ads = ads;
        this.startDate = startDate;
        this.endDate = endDate;
        this.plan = plan;
        this.holeAd = holeAd;
        this.adZone = adZone;
//        this.adzoneses = adzoneses;
    }

    public Integer getContractId() {
        return this.contractId;
    }

    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    public Ads getAds() {
        return this.ads;
    }

    public void setAds(Ads ads) {
        this.ads = ads;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public byte getPlan() {
        return this.plan;
    }

    public void setPlan(byte plan) {
        this.plan = plan;
    }

    public String getHoleAd() {
        return this.holeAd;
    }

    public void setHoleAd(String holeAd) {
        this.holeAd = holeAd;
    }

    public String getAdZone() {
        return this.adZone;
    }

    public void setAdZone(String adZone) {
        this.adZone = adZone;
    }

    public Set getAdzoneses() {
        return Collections.EMPTY_SET;
//        return this.adzoneses;
    }

    public void setAdzoneses(Set adzoneses) {
//        this.adzoneses = adzoneses;
    }

    public boolean isActive() {
        return isActive(System.currentTimeMillis());
    }
    public boolean isActive(long now) {
        boolean started = startDate == null || now > startDate.getTime();
        boolean notExpired = endDate == null || now < endDate.getTime();
        return started && notExpired;
    }

}
