package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DefaultTees generated by hbm2java
 */
@Entity
@Table(name = "default_tees")
public class DefaultTees implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "course", column = @Column(name = "course", nullable = false)),
        @AttributeOverride(name = "number", column = @Column(name = "number", nullable = false))
    })
    private DefaultTeesId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course", nullable = false, insertable = false, updatable = false)
    private Courses courses;

    @Column(nullable = false)
    private int color;

    private String name;

    public DefaultTees() {
    }

    public DefaultTees(DefaultTeesId id, Courses courses, int color, String name) {
        this.id = id;
        this.courses = courses;
        this.color = color;
        this.name = name;
    }

    public DefaultTeesId getId() {
        return this.id;
    }

    public void setId(DefaultTeesId id) {
        this.id = id;
    }

    public Courses getCourses() {
        return this.courses;
    }

    public void setCourses(Courses courses) {
        this.courses = courses;
    }

    public int getColor() {
        return this.color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
