package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FnbOrder generated by hbm2java
 */
@Entity
@Table(name = "fnb_order")
public class FnbOrder implements java.io.Serializable {

    @Id @GeneratedValue
    private Integer orderId;

    private int cartNumber;

    private int currentHole;

    private int orderNumber;

    private int hutNumber;

    private String item;

    private String fnbEmail;

    private String subject;

    private String fnbNumber;

    private String sendContent;

    @Embedded
    private MessageStatus sendStatus;

    public FnbOrder() {
        sendStatus = new MessageStatus();
    }

    public FnbOrder(int currentHole, int cartNumber) {
        sendStatus = new MessageStatus();
        this.currentHole = currentHole;
        this.cartNumber = cartNumber;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public int getCartNumber() {
        return this.cartNumber;
    }

    public void setCartNumber(int cartNumber) {
        this.cartNumber = cartNumber;
    }

    public int getCurrentHole() {
        return this.currentHole;
    }

    public void setCurrentHole(int currentHole) {
        this.currentHole = currentHole;
    }

    public int getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }

    public int getHutNumber() {
        return hutNumber;
    }

    public void setHutNumber(int hutNumber) {
        this.hutNumber = hutNumber;
    }

    public String getItems() {
        return this.item;
    }

    public void setItems(String item) {
        this.item = item;
    }

    public String getFnbEmail() {
        return fnbEmail;
    }

    public void setFnbEmail(String fnbEmail) {
        this.fnbEmail = fnbEmail;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getFnbNumber() {
        return fnbNumber;
    }

    public void setFnbNumber(String fnbNumber) {
        this.fnbNumber = fnbNumber;
    }

    public String getSendContent() {
        return sendContent;
    }

    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }

    public MessageStatus getSendStatus() {
        return sendStatus;
    }

    public void setSendStatus(MessageStatus sendStatus) {
        this.sendStatus = sendStatus;
    }

}
