package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HoleObjectsId generated by hbm2java
 */
@Embeddable
public class HoleObjectsId implements java.io.Serializable {

    @Column(nullable=false)
    private int course;

    @Column(nullable=false)
    private int hole;

    @Column(nullable=false)
    private int id;

    public HoleObjectsId() {
    }

    public HoleObjectsId(int course, int hole, int id) {
        this.course = course;
        this.hole = hole;
        this.id = id;
    }

    public int getCourse() {
        return this.course;
    }

    public void setCourse(int course) {
        this.course = course;
    }

    public int getHole() {
        return this.hole;
    }

    public void setHole(int hole) {
        this.hole = hole;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof HoleObjectsId))
            return false;
        HoleObjectsId castOther = (HoleObjectsId) other;

        return (this.getCourse() == castOther.getCourse())
                && (this.getHole() == castOther.getHole())
                && (this.getId() == castOther.getId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCourse();
        result = 37 * result + this.getHole();
        result = 37 * result + this.getId();
        return result;
    }

}
