package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HolesId generated by hbm2java
 */
@Embeddable
public class HolesId implements java.io.Serializable {

    @Column(nullable = false)
    private int course;

    @Column(nullable = false)
    private int hole;

    public HolesId() {
    }

    public HolesId(int course, int hole) {
        this.course = course;
        this.hole = hole;
    }

    public int getCourse() {
        return this.course;
    }

    public void setCourse(int course) {
        this.course = course;
    }

    public int getHole() {
        return this.hole;
    }

    public void setHole(int hole) {
        this.hole = hole;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof HolesId))
            return false;
        HolesId castOther = (HolesId) other;

        return (this.getCourse() == castOther.getCourse())
                && (this.getHole() == castOther.getHole());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCourse();
        result = 37 * result + this.getHole();
        return result;
    }

}
