package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MenuItems generated by hbm2java
 */
@Entity
@Table(name = "menu_items")
public class MenuItems implements java.io.Serializable {

    @Id @GeneratedValue(strategy = IDENTITY)
    private Integer itemId;

    @Column(nullable = false)
    private String name;

    private String description;

    @Column(nullable = false)
    private float price;

    private String thumb;

    private String picture;

    @Column(nullable = false)
    private int type;

    @Column(nullable = false)
    private boolean active;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false)
    private Date updated;

    public MenuItems() {
        this("", 0, 0, true, new Date());
    }

    public MenuItems(String name, float price, int type, boolean active, Date updated) {
        this.name = name;
        this.price = price;
        this.type = type;
        this.active = active;
        this.updated = updated;
    }

    public MenuItems(String name, String description, float price, String picture, int type, boolean active, Date updated) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.picture = picture;
        this.type = type;
        this.active = active;
        this.updated = updated;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public float getPrice() {
        return this.price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public static MenuItems findById(List<MenuItems> list, int itemId) {
        for (MenuItems mi : list) {
            if (mi.getItemId() != null && mi.getItemId() == itemId) {
                return mi;
            }
        }
        return null;
    }

    public static void setUpdated(List<MenuItems> menuItems, Date date) {
        for (MenuItems i : menuItems) {
            i.setUpdated(date);
        }
    }

}
