package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScoreCard generated by hbm2java
 */
@Entity
@Table(name = "score_card")
public class ScoreCard implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Integer scorecardId;

    private String playerNames;

    private String scores;

    private Integer cartNumber;

    private String email;

    private String holesPlayed;

    private String parValues;

    private int roundId;

    @Embedded
    private MessageStatus sendStatus;

    public ScoreCard() {
        sendStatus = new MessageStatus();
    }

    public ScoreCard(String playerNames, String scores) {
        sendStatus = new MessageStatus();
        this.playerNames = playerNames;
        this.scores = scores;
    }

    public ScoreCard(String playerNames, String scores, Integer cartNumber, String email, Date created) {
        sendStatus = new MessageStatus();
        this.playerNames = playerNames;
        this.scores = scores;
        this.cartNumber = cartNumber;
        this.email = email;
        sendStatus.setCreated(created);
    }

    public Integer getScorecardId() {
        return this.scorecardId;
    }

    public void setScorecardId(Integer scorecardId) {
        this.scorecardId = scorecardId;
    }

    public String getPlayerNames() {
        return this.playerNames;
    }

    public void setPlayerNames(String playerNames) {
        this.playerNames = playerNames;
    }

    public String getScores() {
        return this.scores;
    }

    public void setScores(String scores) {
        this.scores = scores;
    }

    public Integer getCartNumber() {
        return this.cartNumber;
    }

    public void setCartNumber(Integer cartNumber) {
        this.cartNumber = cartNumber;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getHolesPlayed() {
        return holesPlayed;
    }

    public void setHolesPlayed(String holesPlayed) {
        this.holesPlayed = holesPlayed;
    }

    public int getRoundId() {
        return roundId;
    }

    public void setRoundId(int roundId) {
        this.roundId = roundId;
    }

    public String getParValues() {
        return parValues;
    }

    public void setParValues(String parValues) {
        this.parValues = parValues;
    }

    public MessageStatus getSendStatus() {
        return sendStatus;
    }

    public void setSendStatus(MessageStatus sendStatus) {
        this.sendStatus = sendStatus;
    }

}
