package com.stayprime.hibernate.entities;
// Generated Sep 17, 2014 5:18:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeeBoxes generated by hbm2java
 */
@Embeddable
public class TeeBoxes implements java.io.Serializable {

    @Column
    private int number;
    private int color;
    private String distance;

    public TeeBoxes() {
    }

    public TeeBoxes(Holes h, int n) {
        number = n;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public int getColor() {
        return this.color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public String getDistance() {
        return this.distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

}
